{% set name = "ZEO" %}
{% set version = "5.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50f640b36a992f66ed58caf55be80faf26deaccd4f02a84caae3c440f6320133

build:
  entry_points:
    - zeopack=ZEO.scripts.zeopack:main
    - runzeo=ZEO.runzeo:main
    - zeoctl=ZEO.zeoctl:main
    - zeo-nagios=ZEO.nagios:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - setuptools
    - zodb >=5.1.1
    - six
    - transaction >=2.0.3
    - persistent >=4.1.0
    - zc.lockfile
    - zconfig
    - zdaemon
    - zope.interface
    - msgpack-python

test:
  imports:
    - ZEO
    - ZEO.asyncio
    - ZEO.scripts
    - ZEO.tests
    - ZEO.tests.ZEO4
    - ZEO.tests.ZEO4.auth
    - ZEO.tests.ZEO4.zrpc

  commands:
    # no --help option for zeopack: - zeopack --help
    - runzeo --help
    - zeoctl --help
    - zeo-nagios --help
    - pip check

  requires:
    - pip

about:
  home: https://github.com/zopefoundation/ZEO
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: OTHER
  summary: ZEO - Single-server client-server database server for ZODB
  dev_url: https://github.com/zopefoundation/ZEO
  doc_url: https://github.com/zopefoundation/ZEO

extra:
  recipe-maintainers:
    - jan-janssen
