{% set name = "zeo" %}
{% set version = "6.2" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e29c52eb9767d94b270bff4c6eca4c863fcbc46d15323686e6fb71bfe43c7899

build:
  entry_points:
    - zeopack = ZEO.scripts.zeopack:main
    - runzeo = ZEO.runzeo:main
    - zeoctl = ZEO.zeoctl:main
    - zeo-nagios = ZEO.nagios:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools <80
  run:
    - python >={{ python_min }}
    - zodb >=5.1.1
    - transaction >=2.0.3
    - persistent >=4.1.0
    - zc.lockfile
    - zconfig
    - zdaemon
    - zope.interface
    - setuptools <80

test:
  imports:
    - ZEO
  commands:
    - pip check
    # - zeopack --help
    - runzeo --help
    - zeoctl --help
    - zeo-nagios --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zopefoundation/ZEO
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: OTHER
  summary: ZEO - Single-server client-server database server for ZODB
  dev_url: https://github.com/zopefoundation/ZEO
  doc_url: https://github.com/zopefoundation/ZEO

extra:
  recipe-maintainers:
    - jan-janssen
