{% set name = "ZEO" %}
{% set version = "5.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b24f1741857956c31f9f7f02e55b434531add584f4741abd71053316ba1d9ac

build:
  noarch: python
  entry_points:
    - zeopack = ZEO.scripts.zeopack:main
    - runzeo = ZEO.runzeo:main
    - zeoctl = ZEO.zeoctl:main
    - zeo-nagios = ZEO.nagios:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - zodb >=5.1.1
    - six
    - transaction >=2.0.3
    - persistent >=4.1.0
    - zc.lockfile
    - zconfig
    - zdaemon
    - zope.interface

test:
  imports:
    - ZEO
  commands:
    - pip check
    - runzeo --help
    - zeoctl --help
    - zeo-nagios --help
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/ZEO
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: OTHER
  summary: ZEO - Single-server client-server database server for ZODB
  dev_url: https://github.com/zopefoundation/ZEO
  doc_url: https://github.com/zopefoundation/ZEO

extra:
  recipe-maintainers:
    - jan-janssen
