{% set name = "zeo" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ZEO-{{ version }}.tar.gz
  sha256: be238b5abf9ea3396935b33530f66a9afa61ccf8b6b813c2cfdcb2aa18541be7

build:
  entry_points:
    - zeopack = ZEO.scripts.zeopack:main
    - runzeo = ZEO.runzeo:main
    - zeoctl = ZEO.zeoctl:main
    - zeo-nagios = ZEO.nagios:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - zodb >=5.1.1
    - transaction >=2.0.3
    - persistent >=4.1.0
    - zc.lockfile
    - zconfig
    - zdaemon
    - zope.interface

test:
  imports:
    - ZEO
  commands:
    - pip check
    - zeopack --help
    - runzeo --help
    - zeoctl --help
    - zeo-nagios --help
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/ZEO
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: OTHER
  summary: ZEO - Single-server client-server database server for ZODB
  dev_url: https://github.com/zopefoundation/ZEO
  doc_url: https://github.com/zopefoundation/ZEO

extra:
  recipe-maintainers:
    - jan-janssen
