travis:
  secure:
    BINSTAR_TOKEN: HkIdV1ssHFYQePhH2R+hD/x7PEWoOVMgsPLj5PVxXeNk6Rm67+C6UedfiAFoYYkwDLhYVUslK35EJGGlPu48ap2IpQxYHpNgDOpdNiUb3buOyvF0GlCphWRAIT40FHQlYpyo/obIp3dE3Np4FdUmcZeSBObiswgparg2K1w3t1X1RxP3zqckNZHh6ZS2Jth+ryfKtIIOdbIbJpsEKkudypOCzs1/OGYwUASxk97FZVYV44dbgCHM58krCsJX1JKPP6kiL0BVZ67Xrk8TBkY72GzdwlmFb2ren41n4HY/Y5JPYS3ybwOQBQBDVJ715KF8E4kmVMDVlE3FXVYos/7SzKsY7wNhDpraS/lpM/cLOlX6rRyjF4fDZStRvpG4kxpO+gVEhijuPx0aPccHvHZUcTplPLjUFctY9oxxrnevUHvImwo6r31mbjeIBFJCX6PmxzhHaGmROaxeCYq+3bxueLJAuvR0r6VEJHFicmIiIMRjD5IoppftfQwo0KCSimK8Mfpg6gsz2wAt9wH3UCbw0H9koHmJtj2sZeaMtl0H7NA1sBUs9ZkW5gU460KCGpMvWjFr2rZMXbefDEI4KSAtDti3Ls7L9EZitCbvgR8FIpw/3q3IGxBarsLl6B6qCdL+YO5BsZLNoX/oz+ITCLYrmnsIwc4ArTZI72gN9KQrmcI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
