travis:
  secure:
    BINSTAR_TOKEN: YsbjN0FNlSisFOtpW//JHfnBtYhclnZROkX9dPR54XxSc6gJM7uYSnY3fGWZcoUUUN8Sz9bphI2MzAvbTgNAEZtRahlh7X06o0uAaKwMPN66mUSZ4Ci76OeJ4+16NyZ/EKbyft+gm0yI0MsPWhiyBYUkAfUthvipg5qqq9edbA1XkIJN9WgDhRi+BIO37AZzn8EkH3B1RAv4eranAcAT7lGyLS2f7wS6xJm27NIkCk5AfDfSqN1c5AK+OikE7hi5m8n+pD6fXCSKeLv/rSY5vf9/phu2+zMA72zEipHRVXvmUtaQN5hoImet7Yxkz6Hbu5Tuxm0Wx7YCRKPJo79V1qcmkBYrr5jOtgqMFo/1kzSmtVwY2hvTmN1lVTlQ1MWgHVzQaJwj7mnijpgABn9J+4J1pyhcY7DIPe9ZZie9wlvM/or99BtzyUN47f2KgC10SMLlG85aqsEvBxVH3CFHmUc3bk5fIFOtA1fa7fcLdfBBWY1Ad+5faOPibhKnFxFOl19H1mscveLu8Mc2/gg5wFCtIiQFcx6x50F6Xh/P58MPppe4ywUBzIlYkv0+HA0mJ4ipC7yludxw2KiknNM5jli5/VJDbXae4zBDWxHpGSbotc2Xrwp5Kv4TOuRH/T1k/XVEr9hXsmWCnTkXkvz9OgBpqEIsu6K/X/sN16xaIdw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
